export const metadata = {
    title: "Search",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <main>
          {children}
      </main>
    );
  }
  